### ISSUE TITLE
Build image error

### ISSUE THREAD

**Issue by nanxintin** [crowdAI/vizdoom2018-multiplayer-starter-kit#4]
Hi, when I tried to build image, I came across an error.

[Repo2Docker] Looking for repo2docker_config in /home/shao/projects-py3/vizdoom2018-multiplayer-starter-kit
Traceback (most recent call last):
  File "/home/shao/projects-py3/bin/crowdai-repo2docker", line 11, in <module>
    sys.exit(main())
  File "/home/shao/projects-py3/lib/python3.5/site-packages/repo2docker/__main__.py", line 7, in main
    f.start()
  File "/home/shao/projects-py3/lib/python3.5/site-packages/repo2docker/app.py", line 567, in start
    **kwargs_from_env())
  File "/home/shao/projects-py3/lib/python3.5/site-packages/docker/api/client.py", line 113, in __init__
    config_dict=self._general_configs
TypeError: load_config() got an unexpected keyword argument 'config_dict'.

Could anyone give me some advice to solve the error? Thanks.

**Comment by spMohanty** [comment]
@nanxintin : It looks like an issue because of the python docker package.
Can you try to remove the current docker package, and install the latest docker-py by : 
```
pip uninstall docker
pip install -U git+https://github.com/docker/docker-py
```

**Comment by nanxintin** [comment]
@spMohanty Thanks for your reply.
I have follow your advice that uninstall the docker-3.4.1, and install docker-3.5.0.dev0 by "pip install -U git+https://github.com/docker/docker-py ". However,  the same error happens. I try to built the image in the Ubuntu16.04.
It seems that there is still something wrong with my docker.
